jwt:
  accessTokenSecret: j38mdXlEKndX7DVLslV3fj9RvgXh5mTl9Hh2YrcAeOY=
  accessLifetime: 1d
spring:
  application:
    name: vlad-project
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
        maxPageSize: 100
  mail:
    username: artyom.nov.1997artem@yandex.ru
    password: boalxgxbofaipkgn
    host: smtp.yandex.ru
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587

---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:6541/service-db-dev
    username: postgres
    password: pwKj9fzR
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/master.xml

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/master.xml

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:vlad-project;DB_CLOSE_DELAY=-1
    username: user
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false
