logging:
  level:
    root: INFO
    org.springframework: DEBUG
    it.aces.vlad_project: DEBUG
jwt:
  accessTokenSecret: j38mdXlEKndX7DVLslV3fj9RvgXh5mTl9Hh2YrcAeOY=
  accessLifetime: 1d
spring:
  application:
    name: vlad-project
  mail:
    username: artyom.nov.1997artem@yandex.ru
    password: boalxgxbofaipkgn
    host: smtp.yandex.ru
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1:5433/service_db
    username: user
    password: password
    hikari:
      poolName: Hikari
      auto-commit: false
  liquibase:
    change-log: classpath:db/master.xml

server:
  port: 8081

